version: '3.9'
services:
  sql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SQL_SERVER_PASS}
    ports:
      - '1433:1433'
    volumes:
      - sql-volume:/var/opt/mssql
volumes:
  sql-volume: